### ISSUE TITLE
(Bug?)B站链接的og图片均无法正常发出

### ISSUE THREAD

**Issue by medicago087** [koishijs/koishi-plugin-og#1]
![image](https://user-images.githubusercontent.com/68104673/227085199-4cc952fa-7bc8-4cd7-bb1d-199dbfe57627.png)
稳定发出cq码，但点进去图片存在。

**Comment by shigma** [comment]
确实是 bug，要修一下 `//` 前缀的处理

**Comment by shigma** [comment]
已修复。
