### ISSUE TITLE
B站视频的 og:image 无法被解析

### ISSUE THREAD

**Issue by eric2788** [koishijs/koishi-plugin-og#7]
![image](https://github.com/koishijs/koishi-plugin-og/assets/6276840/236998dc-2a75-428c-9e50-a73849192499)

B站使用的是 ``//`` 为开头而非 http/https 那种，导致无法解析

![image](https://github.com/koishijs/koishi-plugin-og/assets/6276840/0075af9b-8864-4de7-86fb-78351e8de764)

可以透过检测是否 // 开头而自行添加 https 字样进行请求从而修复问题

**Comment by eric2788** [comment]
umm如果没时间搞，我可以帮忙提pr

**Comment by eric2788** [comment]
噢... red 协议居然能正常发图，沙盒反而不行

**Comment by shigma** [comment]
既然你这么说那我必然欢迎 PR~

**Comment by eric2788** [comment]
網頁 Referer 問題

**Comment by shigma** [comment]
抱歉浪费你时间了（
